// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#include "hardware/pio.h"

// ----------- //
// quadratureB //
// ----------- //

#define quadratureB_wrap_target 0
#define quadratureB_wrap 13

extern const struct pio_program quadratureB_program;

pio_sm_config quadratureB_program_get_default_config(uint offset);
void quadratureB_program_init(PIO pio, uint sm, uint offset, uint a_pin, uint b_pin);

// ----------- //
// quadratureA //
// ----------- //

#define quadratureA_wrap_target 0
#define quadratureA_wrap 13

extern const struct pio_program quadratureA_program;

pio_sm_config quadratureA_program_get_default_config(uint offset);
void quadratureA_program_init(PIO pio, uint sm, uint offset, uint a_pin, uint b_pin);